sudo: false
language: cpp
matrix:
  include:
    -env: GCC_VERSION=5
    os: linux
    compiler: g++-5
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-5
    before_install: &cmake380
    - curl -o cmake-3.8.0-Linux-x86_64.tar.gz https://cmake.org/files/v3.8/cmake-3.8.0-Linux-x86_64.tar.gz
    - tar -xf cmake-3.8.0-Linux-x86_64.tar.gz
    - export PATH="${PWD}/cmake-3.8.0-Linux-x86_64/bin:${PATH}"
    
    -env: CLANG_VERSION=3.6
    os: linux
    compiler: clang-3.6
    addons:
      apt:
        sources:
        - llvm-toolchain-precise-3.6
        packages:
        - clang-3.6
    before_install: *cmake380
    
before_script:
- mkdir _build
- cd _build
- cmake ..
script:
- cmake --build . -- -j2