language: cpp
compiler:
- gcc
os:
- linux
before_install:
- curl -o cmake-3.8.0-Linux-x86_64.tar.gz https://cmake.org/files/v3.8/cmake-3.8.0-Linux-x86_64.tar.gz
- tar -xf cmake-3.8.0-Linux-x86_64.tar.gz
- export PATH="cmake-3.8.0-Linux-x86_64/bin:${PATH}"
before_script:
- mkdir _build
- cd _build
- cmake ..
script:
- cmake --build .